# Galaxy Calculator 2 appveyor configuration files
# https://ci.appveyor.com/tools/validate-yaml
#https://www.appveyor.com/docs/build-environment/#qt
# https://download.qt.io/snapshots/ifw/installer-framework/30/
version: '{branch}-{build}'

branches:
  only:
    - master

configuration: Release

platform:
  - x64
  - x86

environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu2004
      RUNTIME_LINKAGE: static
      COVERITY_BUILD_CANDIDATE: True
      QT5_32: $HOME/Qt/5.15.2/gcc_32/bin
      QT5_64: $HOME/Qt/5.15.2/gcc_64/bin
      PY_DIR_32: $HOME/venv3.9
      PY_DIR_64: $HOME/venv3.9
      PY_VER: 3.9
      QT_IF_VERSION: '3.1.1'
      PRJLIBS: VCRUNTIME140.dll MSVCP140.dll
      BIN_PRO_RES_NAME: GalaxyCalculator2
      MY_OS: Ubuntu2004
      QIF_PACKAGE_URI: 'packages/com.lightwizzard.galaxycalculator2/data'
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      RUNTIME_LINKAGE: static
      COVERITY_BUILD_CANDIDATE: True
      QT_VERSION: 5.15
      QT5_32:   C:\Qt\5.15.2\mingw81_32
      MINGW_32: C:\Qt\Tools\mingw810_32
      QT5_64:   C:\Qt\5.15.2\mingw81_64
      MINGW_64: C:\Qt\Tools\mingw810_64
      PY_DIR_32: C:\Python38
      PY_DIR_64: C:\Python38-x64
      PY_VER: 3.8
      QT_IF_VERSION: '3.1.1'
      PRJLIBS: VCRUNTIME140.dll MSVCP140.dll
      BIN_PRO_RES_NAME: GalaxyCalculator2
      MY_OS: Windows
      QIF_PACKAGE_URI: 'packages\com.lightwizzard.galaxycalculator2\data'

stack: python %PY_VER%


install:
  - cmd: write-host "install Windows"
  - sh: echo install Unix
  #
  - cmd: if %platform%==x86 set PATH=%PY_DIR_32%;%PY_DIR_32%\Scripts;%PATH%
  - cmd: if %platform%==x86 set PATH=%MINGW_32%\bin;%QT5_32%\bin;%PATH%
  - cmd: if %platform%==x64 set PATH=%PY_DIR_64%;%PY_DIR_64%\Scripts;%PATH%
  - cmd: if %platform%==x64 set PATH=%MINGW_64%\bin;%QT5_64%\bin;%PATH%
  - cmd: if %platform%==x86 call "%QT5_32%\bin\qtenv2.bat"
  - cmd: if %platform%==x64 call "%QT5_64%\bin\qtenv2.bat"
  - cmd: if %platform%==x86 call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars32.bat"
  - cmd: if %platform%==x64 call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars64.bat"
  #- sh: ls $HOME/Qt/5.15.2/Tools/
  # Create our AppVeyor version
  - ps: $env:REPO_NAME =  $env:APPVEYOR_REPO_NAME.Substring($env:APPVEYOR_REPO_NAME.IndexOf('/') + 1)
  - ps: $env:package_version = ("$(git describe --tags --always --long)").trim()
  - ps: Update-AppveyorBuild -Version "$env:package_version-$env:APPVEYOR_BUILD_NUMBER"
  #
  - sh: bash -c "scripts/install.sh"
build_script:
   - sh: echo build_script Unix
   - cmd: write-host "build_script Windows"
   #
   - cmd: cd %APPVEYOR_BUILD_FOLDER%
   - cmd: mkdir build
   - cmd: cd build
   - cmd: mkdir AppDir
   - cmd: if %platform%==x86 qmake -v && qmake ..\%BIN_PRO_RES_NAME%.pro CONFIG+=%configuration% CONFIG+=c++11 DESTDIR=%cd% && mingw32-make && mingw32-make install INSTALL_ROOT=AppDir
   - cmd: if %platform%==x64 qmake -v && qmake ..\%BIN_PRO_RES_NAME%.pro CONFIG+=%configuration% CONFIG+=c++11 DESTDIR=%cd% && mingw32-make && mingw32-make install INSTALL_ROOT=AppDir
   - sh: bash -c "scripts/build-script.sh"
after_build:
  - sh: echo after_build Ubuntu
  - cmd: write-host "after_build Windows"
  - cmd: dir
  - cmd: copy "%APPVEYOR_BUILD_FOLDER%\build\%BIN_PRO_RES_NAME%.exe" "AppDir\%BIN_PRO_RES_NAME%-%MY_OS%-%CONFIGURATION%-%platform%.exe"
  - cmd: windeployqt "AppDir/%BIN_PRO_RES_NAME%.exe" --verbose=2
  #- cmd: for %%I in (%PRJLIBS%) do copy %PRJLIBDIR%\%%I AppDir\
  - cmd: 7z a -tzip "%BIN_PRO_RES_NAME%-%MY_OS%-%CONFIGURATION%-%platform%.zip" AppDir -r
  - cmd: copy "%APPVEYOR_BUILD_FOLDER%\build\%BIN_PRO_RES_NAME%-%MY_OS%-%CONFIGURATION%-%platform%.zip" "%APPVEYOR_BUILD_FOLDER%\
  - cmd: echo APPVEYOR_BUILD_FOLDER=%APPVEYOR_BUILD_FOLDER%
  #- cmd: xcopy /s /e /f "%APPVEYOR_BUILD_FOLDER%\build\AppDir" "%APPVEYOR_BUILD_FOLDER%\%QIF_PACKAGE_URI%"
  #- cmd: C:\Qt\QtIFW-3.1.1\bin\binarycreator.exe --offline-only -c "%APPVEYOR_BUILD_FOLDER%\config\config.xml" -p "%APPVEYOR_BUILD_FOLDER%\packages" "%BIN_PRO_RES_NAME%-Windows-Installer.exe"
  #- cmd: 7z a -tzip "%BIN_PRO_RES_NAME%-Windows-Installer.zip" "%BIN_PRO_RES_NAME%-Windows-Installer.exe"
  - cmd: C:\Qt\Tools\QtInstallerFramework\binarycreator.exe --offline-only -c "%APPVEYOR_BUILD_FOLDER%\config\config.xml" -p "%APPVEYOR_BUILD_FOLDER%\packages" "%BIN_PRO_RES_NAME%-Windows-Installer.exe"
  - cmd: copy *.zip %APPVEYOR_BUILD_FOLDER%
  - cmd: copy *.exe %APPVEYOR_BUILD_FOLDER%
  - cmd: cd %APPVEYOR_BUILD_FOLDER%
  - cmd: echo Current Path is %cd%
  - cmd: dir
  - cmd: write-host "Completed-Build Windows"
  - sh: echo Completed-Build Ubuntu

artifacts:
  - path: '*.zip'
    name: 'ZipInstaller'

deploy:
  - provider: GitHub
    release: continuous
    artifact: 'ZipInstaller'
    draft: false
    prerelease: true
    auth_token:
      secure: 5Kb03ANp7s6KeJKren+ROsEnuCk2tXGby36aqYpG0WV8xfHBg26Td9B4C9jpI/O/
############################################## End of File ####################

