# Galaxy Calculator 2 appveyor configuration files
version: '{branch}-{build}'

branches:
  only:
    - master

#image:
#  - Visual Studio 2019
#  - Ubuntu2004
#  - macos

stack: python 3

environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      RUNTIME_LINKAGE: static
      COVERITY_BUILD_CANDIDATE: True
      #https://www.appveyor.com/docs/build-environment/#qt
      QT5: C:\Qt\5.15.2\mingw81_32
      MINGW: C:\Qt\Tools\mingw810_32
      QT_IF_VERSION: '3.1.1'
      PRJLIBS: VCRUNTIME140.dll MSVCP140.dll
      BIN: GalaxyCalculator2
      MY_OS: Windows
      QIF_PACKAGE_URI: 'packages\com.lightwizzard.galaxycalculator2\data'
      PY_DIR: C:\Python39

init:
  # Create our AppVeyor version
  - ps: $env:commit = $env:appveyor_repo_commit.SubString(0,7)
  - ps: Update-AppveyorBuild -Version ("{0}-{1}-{2}" -f $env:appveyor_repo_branch,$env:appveyor_build_number,$env:commit )
  - cmd: set PATH=%PY_DIR%;%PY_DIR%\Scripts;%PATH%

configuration:
  - release

platform:
  - Win32

before_build:
  - set PATH=%MINGW%\bin;%QT5%\bin;%PATH%
  - '%QT5%\bin\qtenv2.bat'
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars32.bat"

build_script:
  - cd %APPVEYOR_BUILD_FOLDER%
  - mkdir build
  - cd build
  #- ps: if ($isLinux)   { qmake -v && qmake ..\%BIN%.pro CONFIG+=release CONFIG+=c++11 DESTDIR=%cd% && make }
  - qmake -v && qmake ..\%BIN%.pro CONFIG+=release CONFIG+=c++11 DESTDIR=%cd% && mingw32-make
    
after_build:
  # Add a link to the build output within the source directory. This is needed because AppVeyor does
  # not support extracting artifacts from out-of-source build directories. See 'artifacts' below.
  - echo after_build
  - dir
  - mkdir deploy
  - copy "%APPVEYOR_BUILD_FOLDER%\build\%BIN%.exe" "deploy\%BIN%.exe"
  - windeployqt "deploy/%BIN%.exe" --verbose=2
  #- for %%I in (%PRJLIBS%) do copy %PRJLIBDIR%\%%I deploy\
  - 7z a -tzip "%BIN%-%MY_OS%.zip" deploy -r
  - copy "%APPVEYOR_BUILD_FOLDER%\build\%BIN%-%MY_OS%.zip" "%APPVEYOR_BUILD_FOLDER%\%BIN%-%MY_OS%.zip"
  - echo APPVEYOR_BUILD_FOLDER=%APPVEYOR_BUILD_FOLDER%
  #- xcopy /s /e /f "%APPVEYOR_BUILD_FOLDER%\build\deploy" "%APPVEYOR_BUILD_FOLDER%\%QIF_PACKAGE_URI%"
  #- C:\Qt\QtIFW-3.1.1\bin\binarycreator.exe --offline-only -c "%APPVEYOR_BUILD_FOLDER%\config\config.xml" -p "%APPVEYOR_BUILD_FOLDER%\packages" "%BIN%-Windows-Installer.exe"
  #- 7z a -tzip "%BIN%-Windows-Installer.zip" "%BIN%-Windows-Installer.exe"
  - copy *.zip %APPVEYOR_BUILD_FOLDER%
  - copy *.exe %APPVEYOR_BUILD_FOLDER%
  - cd %APPVEYOR_BUILD_FOLDER%
  #- del %APPVEYOR_BUILD_FOLDER%\%BIN%.pro
  - echo Current Path is %cd%
  - dir
  - echo Completed-Build

artifacts:
  - path: '%BIN%*.zip'  
    name: 'ZipInstaller'
  - path: '%BIN%*.exe'
    name: 'ExecutableFile'

deploy:
  - provider: GitHub
    release: continuous
    artifact: 'ZipInstaller'
    draft: false
    prerelease: true
    auth_token:
      secure: $($env:AppVeyorEnvVar)
  - provider: GitHub
    release: continuous
    artifact: 'ExecutableFile'
    draft: false
    prerelease: true
    auth_token:
      secure: $($env:AppVeyorEnvVar)
############################################## End of File ####################

